#!/bin/bash

usage ()
{
      echo "Usage:    pve-snap --mode --storage=STORAGENAME [--leave=NUMBER]"
      echo
      echo "Example:  pve-snap --weekly --storage=ceph --leave=2"
      echo "     or:  pve-snap --yearly --storage=lvm"
      echo "     or:  pve-snap -d -s stor -l 4"
      echo
      echo "Arguments:"
      echo "    -d, --daily                 Run this script in mode for daily autosnapshots"
      echo "    -w, --weekly                Run this script in mode for weekly autosnapshots"
      echo "    -m, --monthly               Run this script in mode for monthly autosnapshots"
      echo "    -y, --yearly                Run this script in mode for yearly autosnapshots"
      echo "    -s, --storage=STORAGENAME   Specify the storage name for which will be used auto snapshots"
      echo "                                (0 or not specified will enable for all"
      echo "    -l, --leave=NUMBER          Specify the number of snapshots which should will leave, anything longer will be removed"
      echo "                                (0 or not specified will disable removing snapshots)"
      echo
      exit
}

loadkeys ()
{
while [ 1 ] ; do 
    if [ "$1" = "--daily" ] || [ "$1" = "-d" ] ; then 
        mode="daily"
        break
    elif [ "$1" = "--weekly" ] || [ "$1" = "-w" ] ; then 
        mode="weekly"
        break
    elif [ "$1" = "--monthly" ] || [ "$1" = "-m" ] ; then
        mode="monthly"
        break
    elif [ "$1" = "--yearly" ] || [ "$1" = "-y" ] ; then
        mode="yearly"
        break
    else 
        echo -e "\nMode is not set\n"
        usage
    fi
done

while [ 2 ] ; do 
    if [ "${2#--storage=}" != "$2" ] ; then  
        storage="${2#--storage=}" 
        break
    elif [ "$2" = "-s" ] ; then 
        shift ; storage="$2" 
        break
    else 
        storage=0
        break
    fi
done

while [ 3 ] ; do 
    if [ "${3#--leave=}" != "$3" ] ; then  
        leave=${3#--leave=} 
        break
    elif [ "$3" = "-l" ] ; then 
        shift ; leave=$3 
        break
    else 
        shift ; leave=0 
        break
    fi
done
}

gensnapname ()
{
    if [ $mode == "daily" ] ; then
#        snapname="autodaily$(date +%y%m%d)"
        snapname="autodaily$(date +%y%m%d%H%M%S)" #for test
    elif [ $mode == "weekly" ] ; then
#        snapname="autoweekly$(date +%y%m%d)"
        snapname="autoweekly$(date +%y%m%d%H%M%S)" #for test
    elif [ $mode == "monthly" ] ; then
#        snapname="automonthly$(date +%y%m%d)"
        snapname="automonthly$(date +%y%m%d%H%M%S)" #for test
    elif [ $mode == "yearly" ] ; then
#        snapname="autoyearly$(date +%y%m%d)"
        snapname="autoyearly$(date +%y%m%d%H%M%S)" #for test
    fi
}

printkeys ()
{
echo
echo "mode:" $mode
echo "storage:" $storage
echo "leave:" $leave
echo
}


getvms ()
{
vms=($(qm list | awk '{print$1}' | sed 1d))
}

autosnapshot ()
{
for vm in "${vms[@]}"
do
    echo vm: $vm #for test

    storagecheck=($(sed '/^\[.*\]$/q' /etc/pve/nodes/$(hostname)/qemu-server/$vm.conf | sed '$d' | grep -ci "$storage:$vm/vm-$vm"))

    if [[ "$storagecheck" > "0" ]] ; then
        echo "Creating $snapname for $vm"
        qm snapshot $vm $snapname
    fi
   # snapshots=($(grep -Po "(?<=\[).*(?=\])" "/etc/pve/nodes/$(hostname)/qemu-server/$vm.conf"))
   # for snap in "${snapshots[@]}"
   # do
   #    echo $snap #for test
   # done

done
}

loadkeys $1 $2 $3
printkeys 
gensnapname
getvms
autosnapshot
